#!/bin/bash

TARGET=/tmp/syscoin-update
if [ "$1" = "" ]
then
	read -e -p "Syscoin Release Version: " VERSION
	if [ "$VERSION" = "" ]; then
		echo "Didn't specify version. Exiting."
		exit 1
	fi
else
	VERSION=$1
fi
mkdir $TARGET
cd $TARGET

wget https://github.com/syscoin/syscoin/releases/download/$VERSION/SHA256SUMS.asc
wget https://github.com/syscoin/syscoin/releases/download/$VERSION/syscoin-$VERSION-x86_64-linux-gnu.tar.gz
sha256sum --status --ignore-missing -c SHA256SUMS.asc
if [ $? -eq 0 ]
then
	tar xzf syscoin-$VERSION-x86_64-linux-gnu.tar.gz syscoin-$VERSION/bin/syscoin-cli -O > syscoin-cli
	tar xzf syscoin-$VERSION-x86_64-linux-gnu.tar.gz syscoin-$VERSION/bin/syscoind -O > syscoind
	rm syscoin-$VERSION-x86_64-linux-gnu.tar.gz
	chmod +x syscoin*
	sudo chown root:root syscoin*
	sudo rm /usr/local/bin/syscoin*
	sudo mv syscoin* /usr/local/bin/
	echo "Successfully updated";
fi
cd -
rm -rf $TARGET
