#!/bin/bash

TARGET=/tmp/syscoin-update


read -e -p "Syscoin Core Release Version: " VERSION
if [ "$VERSION" = "" ]; then
	echo "Didn't specify version. Exiting."
	exit 1
fi

mkdir $TARGET
cd $TARGET

wget https://github.com/syscoin/syscoin/releases/download/$VERSION/syscoincore-$VERSION-x86_64-linux-gnu.tar.gz
tar -xzf *.gz
sudo mv syscoincore-$VERSION/bin/* /usr/local/bin/

cd -
rm -rf $TARGET
